#!/usr/bin/python3
import rospy
from geometry_msgs.msg import PointStamped, Vector3, Pose, PoseWithCovarianceStamped, PoseStamped

def publish_fix():
    rospy.init_node('initial_pose_publisher')
    pub = rospy.Publisher('initialpose', PoseWithCovarianceStamped, queue_size=10)
    rate = rospy.Rate(2) # 10hz
    idx = 0
    while not rospy.is_shutdown() and idx < 20:
        msg = PoseWithCovarianceStamped()
        msg.header.frame_id = "map"
        msg.header.stamp = rospy.Time.now()
        msg.pose.pose.position.x = -0.018522188424247608
        msg.pose.pose.position.y = -0.4486397848721084
        msg.pose.pose.position.z = 0
        msg.pose.pose.orientation.x = 0
        msg.pose.pose.orientation.y = 0
        msg.pose.pose.orientation.z = -0.01541395483644314
        msg.pose.pose.orientation.w = 0.9998811979411855
        pub.publish(msg)
        idx += 1
        rate.sleep()


if __name__ == "__main__":
    try:
        publish_fix()
    except rospy.ROSInterruptException:
        pass
